# k3d Local Testing Configuration
# Optimized for local development on laptop/workstation

global:
  domain: local.test
  namespace: lfh-dev
  environment: development

  gateway:
    name: shared-gateway
    namespace: gateway-system

  # Use k3d's built-in storage
  storage:
    provider: local-path
    className: local-path

# ===== CORE: HapiHub (Minimal) =====
hapihub:
  enabled: true
  replicas: 1  # Single replica for testing

  image:
    tag: "latest"  # OK for local testing

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  autoscaling:
    enabled: false

  gateway:
    hostname: api.local.test

# ===== CORE: MyCureApp =====
mycureapp:
  enabled: true
  replicas: 1

  image:
    repository: ghcr.io/mycurelabs/mycureapp
    pullPolicy: IfNotPresent
    tag: "10.0.19"

  securityContext:
    readOnlyRootFilesystem: false  # Disabled for local testing (entrypoint needs to write config.json)

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# ===== OPTIONAL: Syncd (Disabled) =====
syncd:
  enabled: false  # Save resources

# ===== CORE: MongoDB (Single-node ReplicaSet) =====
mongodb:
  enabled: true
  architecture: replicaset  # Single-node replicaset for testing
  replicaCount: 1

  # Override image to use rolling tag (fixes ImagePullBackOff)
  image:
    tag: "7.0"  # Rolling tag - always latest MongoDB 7.0.x

  persistence:
    enabled: true
    storageClass: local-path
    size: 1Gi  # Minimal for testing

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

# ===== OPTIONAL: Typesense (Disabled) =====
typesense:
  enabled: false

# ===== OPTIONAL: MinIO (Disabled - Too Heavy) =====
minio:
  enabled: false
  # Use external S3 or skip file uploads in testing

# ===== OPTIONAL: Mailpit (Enabled for Email Testing) =====
mailpit:
  enabled: true  # Good for local email testing

# ===== External Secrets (Simplified for Local) =====
externalSecrets:
  enabled: false  # Use plain Kubernetes Secrets for local testing
  # Or use SOPS for encrypted local secrets

# ===== Monitoring (Disabled - Too Heavy) =====
monitoring:
  enabled: false

# ===== Backup (Disabled for Local) =====
backup:
  enabled: false

# ===== Network Policies (Optional for Local) =====
networkPolicies:
  enabled: false  # Can enable to test policies

# ===== Pod Security Standards =====
podSecurityStandards:
  enabled: true  # Test PSS compliance
  level: restricted

# ===== Autoscaling (Disabled) =====
autoscaling:
  enabled: false

# ===== Resource Quotas (Disabled) =====
resourceQuotas:
  enabled: false

# Notes for k3d Testing:
# - Minimal resources (laptop-friendly)
# - Single replicas (no HA overhead)
# - Single-node MongoDB replicaset (consistent with prod)
# - No MinIO (too heavy)
# - Monitoring disabled (save RAM)
# - Local storage only
# - Perfect for development and testing
