# Default values for MyCureApp chart
# Override these values in config/{client}/values-{env}.yaml

global:
  domain: example.com
  namespace: example-prod
  environment: production
  gateway:
    name: shared-gateway
    namespace: gateway-system

enabled: true

replicaCount: 2

image:
  repository: ghcr.io/mycurelabs/mycureapp
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101  # nginx user
  fsGroup: 101
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  annotations: {}

gateway:
  enabled: true
  hostname: ""  # Empty = uses app.{global.domain}
  parentRefs:
    - name: shared-gateway
      namespace: gateway-system

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

livenessProbe:
  enabled: true
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 1

nodeSelector: {}
tolerations: []
affinity: {}

# Frontend configuration (injected at build time or via ConfigMap)
config:
  VUE_APP_API_URL: ""  # Will be set to HapiHub URL
  VUE_APP_ENVIRONMENT: production

networkPolicy:
  enabled: true
  policyTypes:
    - Ingress
    - Egress

serviceMonitor:
  enabled: false
  interval: 30s
  path: /metrics
