# Production Medium Profile
# For: 5-15 clients, 50k-200k patients, 500GB-2TB data
# Cluster: 5 × m6i.xlarge (4 vCPU, 16GB RAM)
# Monthly cost: ~$800-1200

global:
  domain: CHANGEME.com
  namespace: CHANGEME-prod
  environment: production

# Core: Monobase API
api:
  enabled: true
  image:
    repository: ghcr.io/YOUR-ORG/monobase-api
    tag: "5.215.2"
  replicas: 3
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 2
      memory: 4Gi

# Core: Monobase Account Frontend
account:
  enabled: true
  replicas: 2
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

# Optional: API Worker
# api-worker (removed):
  enabled: true
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi

# Core: MongoDB
postgresql:
  enabled: true
  architecture: replicaset
  replicaCount: 3
  persistence:
    size: 200Gi
  resources:
    requests:
      cpu: 1.5
      memory: 6Gi
    limits:
      cpu: 3
      memory: 8Gi

# Optional: Typesense
# typesense (removed):
  enabled: true
  replicas: 3
  persistence:
    size: 50Gi
  resources:
    requests:
      cpu: 750m
      memory: 1.5Gi
    limits:
      cpu: 2
      memory: 3Gi

# Optional: MinIO (standalone for medium)
minio:
  enabled: true
  mode: standalone
  persistence:
    size: 500Gi
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 2
      memory: 4Gi

# Monitoring recommended
monitoring:
  enabled: true
  prometheus:
    retention: 15d
    storage: 50Gi

# Backup
backup:
  enabled: true
  schedules:
    hourly:
      enabled: true
      retention: 72h
    daily:
      enabled: true
      retention: 720h

# Security
networkPolicies:
  enabled: true
podSecurityStandards:
  enabled: true
  level: restricted

# Autoscaling
autoscaling:
  enabled: true
  api:
    minReplicas: 3
    maxReplicas: 10
  account:
    minReplicas: 2
    maxReplicas: 5
  # api-worker (removed):
    minReplicas: 2
    maxReplicas: 5
