# Longhorn Recurring Backup Jobs
# Tier 1: Hourly snapshots (fast recovery)
# Tier 2: Daily backups to S3 (medium recovery)

---
# Hourly Snapshot Job (Tier 1 - Fast Recovery)
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-hourly
  namespace: longhorn-system
spec:
  cron: "0 * * * *"  # Every hour
  task: snapshot
  groups:
    - default
  retain: 72  # Keep 72 hours (3 days)
  concurrency: 2
  labels:
    tier: tier1-fast
    backup-type: snapshot

---
# Daily Backup Job (Tier 2 - To S3)
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  cron: "0 2 * * *"  # Daily at 2 AM
  task: backup
  groups:
    - default
  retain: 30  # Keep 30 days
  concurrency: 2
  labels:
    tier: tier2-daily
    backup-type: s3-backup

---
# Weekly Full Backup (Tier 3 - Long-term Archive)
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-weekly
  namespace: longhorn-system
spec:
  cron: "0 3 * * 0"  # Weekly on Sunday at 3 AM
  task: backup
  groups:
    - default
  retain: 12  # Keep 12 weeks (~3 months)
  concurrency: 1
  labels:
    tier: tier3-archive
    backup-type: s3-backup

---
# Backup Target Configuration Secret
# Create this secret with your S3 credentials
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-credentials
  namespace: longhorn-system
type: Opaque
stringData:
  # For AWS S3
  AWS_ACCESS_KEY_ID: ""  # From External Secrets
  AWS_SECRET_ACCESS_KEY: ""  # From External Secrets
  AWS_ENDPOINTS: https://s3.amazonaws.com
  
  # For S3-compatible (MinIO, etc.)
  # AWS_ACCESS_KEY_ID: ""
  # AWS_SECRET_ACCESS_KEY: ""
  # AWS_ENDPOINTS: https://s3.your-domain.com
  # VIRTUAL_HOSTED_STYLE: "false"

---
# Volume Group for Critical Data (hourly backups)
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-critical-hourly
  namespace: longhorn-system
spec:
  cron: "0 * * * *"  # Every hour
  task: snapshot
  groups:
    - critical
  retain: 168  # Keep 1 week
  concurrency: 3
  labels:
    tier: tier1-fast
    priority: critical

---
# Backup Target Configuration
# Configure via Longhorn UI or kubectl:
#
# kubectl -n longhorn-system patch settings.longhorn.io backup-target \
#   --type=merge \
#   --patch='{"value": "s3://backup-bucket@us-east-1/"}'
#
# kubectl -n longhorn-system patch settings.longhorn.io backup-target-credential-secret \
#   --type=merge \
#   --patch='{"value": "longhorn-backup-credentials"}'

---
# Usage Instructions:
#
# 1. Label volumes for specific backup schedules:
#    - default: Standard backup (hourly snapshot, daily S3)
#    - critical: Critical data (hourly snapshot + hourly S3)
#
# 2. Label a PVC:
#    kubectl label pvc mongodb-data-mongo-0 \
#      recurring-job.longhorn.io/source=enabled \
#      recurring-job-group.longhorn.io/default=enabled
#
# 3. For critical volumes:
#    kubectl label pvc mongodb-data-mongo-0 \
#      recurring-job-group.longhorn.io/critical=enabled
#
# 4. Verify backup jobs:
#    kubectl get recurringjobs -n longhorn-system
#
# 5. List backups:
#    kubectl get backups -n longhorn-system
#
# 6. Restore from backup:
#    - Via Longhorn UI: Backup tab → Select backup → Restore
#    - Via kubectl: Create new Volume from backup
#
# 7. Test restore procedure monthly!

---
# Backup Retention Summary:
#
# Tier 1 (Snapshots):
#   - Frequency: Hourly
#   - Retention: 72 hours (3 days)
#   - Storage: Local (Longhorn nodes)
#   - Recovery Time: ~5 minutes
#
# Tier 2 (Daily S3):
#   - Frequency: Daily
#   - Retention: 30 days
#   - Storage: S3 (off-cluster)
#   - Recovery Time: ~1 hour
#
# Tier 3 (Weekly Archive):
#   - Frequency: Weekly
#   - Retention: 12 weeks (~3 months)
#   - Storage: S3 (off-cluster)
#   - Recovery Time: ~2 hours
#
# Total Protection: 3 days local + 30 days daily + 90 days weekly
