# Longhorn Encrypted StorageClass with 3-Replica Policy
# This is the primary StorageClass for all StatefulSets

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  # Replication settings
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"

  # Data locality (disabled for best HA, "best-effort" for performance)
  dataLocality: "disabled"

  # Filesystem type
  fsType: "ext4"

  # Disk selector (optional - use specific disks)
  # diskSelector: "ssd,fast"

  # Node selector (optional - use specific nodes)
  # nodeSelector: "storage-node=true"

  # Encryption settings
  # Longhorn uses Linux dm-crypt for volume encryption
  encrypted: "false"  # Set to "true" to enable encryption at rest
  # When encrypted=true, create a Secret with encryption passphrase:
  # kubectl create secret generic longhorn-crypto --from-literal=CRYPTO_KEY_VALUE=<passphrase> -n longhorn-system

  # Backup settings
  recurringJobSelector: '[{"name":"backup-daily","isGroup":false}]'

  # Performance settings
  replicaAutoBalance: "least-effort"
  unmapMarkSnapChainRemoved: "enabled"

---
# Optional: Fast StorageClass (2 replicas, SSD)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-fast
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  dataLocality: "best-effort"
  fsType: "ext4"
  diskSelector: "ssd"
  encrypted: "false"
  replicaAutoBalance: "least-effort"

---
# Optional: Archive StorageClass (1 replica, slower disks OK)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-archive
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  dataLocality: "disabled"
  fsType: "ext4"
  encrypted: "false"
  replicaAutoBalance: "disabled"

---
# Encryption Instructions:
#
# To enable encryption at rest:
# 1. Create encryption secret:
#    kubectl create secret generic longhorn-crypto \
#      --from-literal=CRYPTO_KEY_VALUE=$(openssl rand -base64 32) \
#      -n longhorn-system
#
# 2. Set encrypted: "true" in StorageClass parameters
#
# 3. Reference the secret in defaultSettings:
#    defaultSettings:
#      systemManagedComponentsNodeSelector: "storage=true"
#
# 4. For HIPAA compliance:
#    - Use encrypted: "true"
#    - Store CRYPTO_KEY_VALUE in External Secrets (KMS)
#    - Enable audit logging
#    - Rotate encryption keys periodically (every 90 days)
