{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "syncd.fullname" . }}
  namespace: {{ include "syncd.namespace" . }}
  labels:
    {{- include "syncd.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.NODE_ENV | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  PORT: {{ .Values.config.PORT | quote }}
{{- end }}
