{{- if and .Values.enabled .Values.minio.enabled .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "hapihub.fullname" . }}-minio
  namespace: {{ include "hapihub.namespace" . }}
  labels:
    {{- include "hapihub.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  parentRefs:
    - name: {{ include "hapihub.gateway.name" . }}
      namespace: {{ include "hapihub.gateway.namespace" . }}
  hostnames:
    - {{ .Values.minio.gateway.hostname | default (printf "storage.%s" .Values.global.domain) }}
  rules:
    # S3 API and MinIO Console
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Release.Name }}-minio
          port: 9000
          weight: 1
      
      # Rate limiting for public file access
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.envoyproxy.io
            kind: BackendTrafficPolicy
            name: minio-rate-limit

---
# BackendTrafficPolicy for MinIO Rate Limiting
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: minio-rate-limit
  namespace: {{ include "hapihub.namespace" . }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ include "hapihub.fullname" . }}-minio
  
  rateLimit:
    type: Global
    global:
      rules:
        # Per-IP download rate limit
        - limit:
            requests: 100
            unit: Second
          clientSelectors:
            - headers:
                - name: X-Forwarded-For
                  type: Distinct
        
        # Burst limit
        - limit:
            requests: 1000
            unit: Minute
          clientSelectors:
            - headers:
                - name: X-Forwarded-For
                  type: Distinct
{{- end }}
