apiVersion: v2
name: mycureapp
description: MyCureApp Frontend - Custom Helm chart for Monobase Infrastructure
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - frontend
  - vue
  - mycureapp
home: https://github.com/YOUR-ORG/monobase-infra
sources:
  - https://github.com/YOUR-ORG/mycureapp
maintainers:
  - name: Your Organization
    email: devops@example.com
