# External Secrets Operator - Helm Values
# Chart: https://charts.external-secrets.io
# Version: 0.9.x+

# Deployment replicas
replicaCount: 2  # HA

# Image settings
image:
  repository: ghcr.io/external-secrets/external-secrets
  pullPolicy: IfNotPresent
  tag: ""  # Uses chart appVersion

# Resources
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

podSecurityContext:
  fsGroup: 1000

# Service account
serviceAccount:
  create: true
  annotations: {}
    # For AWS IRSA (IAM Roles for Service Accounts):
    # eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/external-secrets-role
    # For GCP Workload Identity:
    # iam.gke.io/gcp-service-account: external-secrets@project-id.iam.gserviceaccount.com
    # For Azure Workload Identity:
    # azure.workload.identity/client-id: "00000000-0000-0000-0000-000000000000"

# Affinity for HA
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: external-secrets
          topologyKey: kubernetes.io/hostname

# Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Monitoring
metrics:
  enabled: true
  service:
    enabled: true
    port: 8080
  serviceMonitor:
    enabled: false  # Enable when monitoring stack is deployed

# Webhook (for validation)
webhook:
  enabled: true
  replicaCount: 2
  
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Cert Controller (manages webhook certificates)
certController:
  enabled: true
  replicaCount: 1
  
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

# CRD installation
installCRDs: true

# Concurrent reconciles (how many ExternalSecrets to process at once)
concurrent: 3

# Leader election
leaderElect: true

# Extra environment variables (optional)
extraEnv: []
  # - name: AWS_REGION
  #   value: us-east-1

# Extra volumes (for custom CA certificates, etc.)
extraVolumes: []
extraVolumeMounts: []

# Tolerations and node selector
tolerations: []
nodeSelector: {}

# Priority class
priorityClassName: ""

# Enable/disable features
controllerClass: ""  # Leave empty for default

# RBAC
rbac:
  create: true

# Pod labels
podLabels: {}

# Pod annotations
podAnnotations: {}

# Service annotations
service:
  annotations: {}

# Installation instructions:
# helm repo add external-secrets https://charts.external-secrets.io
# helm install external-secrets external-secrets/external-secrets \
#   -n external-secrets-system --create-namespace \
#   -f helm-values.yaml

# Post-installation:
# 1. Create SecretStore (see secretstore/ directory)
# 2. Create ExternalSecret resources (in application Helm charts)
# 3. Verify sync: kubectl get externalsecrets -A
