{{- if and .Values.falco.enabled .Values.falco.rules.enabled }}
# ArgoCD Application: Falco Custom Rules
# Sync Wave 1 - Deploy custom rules after Falco DaemonSet
# Only deployed if falco.enabled=true AND falco.rules.enabled=true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco-rules
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: {{ .Values.argocd.targetRevision | default "main" }}
    path: infrastructure/security-tools/falco/rules
    directory:
      recurse: false
      include: '{api-rules.yaml,database-rules.yaml}'

  destination:
    server: https://kubernetes.default.svc
    namespace: falco

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 3m
{{- end }}
