{{- if .Values.kyverno.enabled }}
# ArgoCD Application: Kyverno
# Sync Wave 0 - Deploy policy engine (cluster-wide)
# Only deployed if kyverno.enabled=true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: {{ .Values.kyverno.version | default "3.2.0" }}
    helm:
      releaseName: kyverno

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /status
{{- end }}
