name: Helm Unit Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'charts/**'
      - 'config/**'
      - '.github/workflows/helm-test.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'charts/**'
      - 'config/**'

jobs:
  helm-unittest:
    name: Helm Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.14.0'

      - name: Install Helm unittest plugin
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest

      - name: Run Monobase API unit tests
        run: |
          echo "Running Monobase API chart unit tests..."
          if [ -d "charts/api/tests" ]; then
            helm unittest charts/api
          else
            echo "⚠️ No tests found for Monobase API (charts/api/tests/ not found)"
            echo "📝 Consider adding unit tests for better coverage"
          fi

      - name: Run API Worker unit tests
        run: |
          echo "Running API Worker chart unit tests..."
          if [ -d "charts/api/tests" ]; then
            helm unittest charts/api
          else
            echo "⚠️ No tests found for API Worker"
          fi

      - name: Run Monobase Account unit tests
        run: |
          echo "Running Monobase Account chart unit tests..."
          if [ -d "charts/account/tests" ]; then
            helm unittest charts/account
          else
            echo "⚠️ No tests found for Monobase Account"
          fi

  template-validation:
    name: Template Rendering Validation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: [api, api, account]
        config: [production, staging]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.14.0'

      - name: Test template rendering
        run: |
          echo "Testing ${{ matrix.chart }} with ${{ matrix.config }} config..."
          helm template test charts/${{ matrix.chart }} \
            --values config/example.com/values-${{ matrix.config }}.yaml \
            --dry-run > /tmp/${{ matrix.chart }}-${{ matrix.config }}.yaml

          echo "✓ Template rendered successfully"
          echo "Generated $(wc -l < /tmp/${{ matrix.chart }}-${{ matrix.config }}.yaml) lines of manifests"

      - name: Validate generated manifests
        run: |
          echo "Validating Kubernetes manifests..."
          kubectl apply --dry-run=client \
            -f /tmp/${{ matrix.chart }}-${{ matrix.config }}.yaml \
            2>&1 | tee /tmp/validation.log

          if grep -i "error" /tmp/validation.log; then
            echo "❌ Validation failed"
            exit 1
          fi

          echo "✓ All manifests are valid"

  dependency-check:
    name: Check Helm Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.14.0'

      - name: Check Monobase API dependencies
        run: |
          cd charts/api
          if [ -f "Chart.yaml" ] && grep -q "dependencies:" Chart.yaml; then
            echo "Checking dependencies for Monobase API..."
            helm dependency list
            helm dependency build
          else
            echo "No dependencies defined for Monobase API"
          fi

      - name: Check API Worker dependencies
        run: |
          cd charts/api
          if [ -f "Chart.yaml" ] && grep -q "dependencies:" Chart.yaml; then
            echo "Checking dependencies for API Worker..."
            helm dependency list
            helm dependency build
          else
            echo "No dependencies defined for API Worker"
          fi

      - name: Check Monobase Account dependencies
        run: |
          cd charts/account
          if [ -f "Chart.yaml" ] && grep -q "dependencies:" Chart.yaml; then
            echo "Checking dependencies for Monobase Account..."
            helm dependency list
            helm dependency build
          else
            echo "No dependencies defined for Monobase Account"
          fi

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [helm-unittest, template-validation, dependency-check]
    if: always()
    steps:
      - name: Check all tests
        run: |
          echo "Helm test results:"
          echo "Unit Tests: ${{ needs.helm-unittest.result }}"
          echo "Template Validation: ${{ needs.template-validation.result }}"
          echo "Dependency Check: ${{ needs.dependency-check.result }}"
