apiVersion: v2
name: syncd
description: Syncd Real-time Sync Service - Custom Helm chart for Monobase Infrastructure
type: application
version: 1.0.0
appVersion: "5.130.7"
keywords:
  - sync
  - real-time
  - offline-first
  - syncd
home: https://github.com/YOUR-ORG/monobase-infra
sources:
  - https://github.com/YOUR-ORG/syncd
maintainers:
  - name: Your Organization
    email: devops@example.com
